Adição de página de Eventos
pyladiesrecife/site pull request #58
Opened 2022-10-08 15:34 UTC by nathaliavc

Transformar sessão de eventos em uma página

Issue #32

2022-10-08 19:52 UTC, naanadr commented
Aprovar antes o Pull Request #43 antes desse aqui. 

Enquanto isso @nathaliavc tu pode colocar um print de como ficou ?

2022-10-08 19:53 UTC, naanadr requested changes

2022-10-08 19:53 UTC, naanadr commented on eventos.html
> +    <meta name="author" content="PyLadies RP">
Coloca o nome do PyLadies da gente

2022-10-08 20:43 UTC, naanadr commented
Atualiza o seu fork e a sua branch com o conteúdo atualizado do site, por favor. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

O seu arquivo tem algumas coisas desatualizadas

2022-10-08 23:09 UTC, nathaliavc commented
<img width="955" alt="image" src="https://user-images.githubusercontent.com/115354968/194730765-aebe13d8-2a22-4781-a29c-2597e1671de7.png">
Olá, desculpa a demora! Aqui segue a imagem e já atualizei minha branch :)

2022-10-12 00:05 UTC, naanadr requested changes

2022-10-12 00:05 UTC, naanadr commented on eventos.html
> +    <meta name="description" content="Ramo local do PyLadies cujo objetivo é propagar em Ribeirão Preto e região os ideais das PyLadies e da comunidade Python.">
```suggestion
    <meta name="description" content="Ramo local do PyLadies cujo objetivo é propagar em Recife e região os ideais das PyLadies e da comunidade Python.">
```

2022-10-12 00:05 UTC, naanadr commented on eventos.html
> +    <meta name="author" content="PyLadies RP">
```suggestion
    <meta name="author" content="PyLadies Recife">
```

2022-10-12 00:05 UTC, naanadr commented on eventos.html
> +    <title> PyLadies RP</title>
```suggestion
    <title> PyLadies Recife</title>
```

2022-10-12 00:05 UTC, naanadr commented on eventos.html
> +    </footer>
```suggestion
   <footer style="background-color:#d67f7f;">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; PyLadies Recife 2022</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">

                        <li><a href="https://pt-br.facebook.com/pyladiesrecife/" target="_blank"><i class="fa fa-facebook"></i></a>
                        </li>
                        <!-- <li><a href="#"><i class="fa fa-linkedin" target="_blank"></i></a> -->
                        <!-- </li> -->
                        <li><a href="https://github.com/pyladiesrecife" target="_blank"><i class="fa fa-github-square"></i></a>
                        </li>
                    </ul>
                </div>
               <!--  <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                        <li><a href="#services">Sing Up</a>
                        </li>
                        <li><a href="#services">Log In</a>
                        </li>
                    </ul>
                </div> -->
            </div>
        </div>
    </footer>
```

2022-10-12 00:05 UTC, naanadr commented on index.html
> +              			<a href="eventos.html" target="_blank">Ver mais Eventos</a>
```suggestion
              			<a href="eventos.html" target="_blank">Ver todos os Eventos</a>
```

2022-10-12 22:55 UTC, nathaliavc commented
Boa noite! Comitei as mudanças pedidas

2022-10-15 18:19 UTC, naanadr approved these changes

2022-10-15 18:23 UTC, merged