Altera o título da sessão de eventos
pyladiesrecife/site pull request #60
Opened 2022-10-08 15:47 UTC by kailanefelix

O título anterior era cursivo, vermelho e centralizado. Essas alterações colocam no padrão PyLadies Recife 💙🚀

2022-10-08 20:14 UTC, naanadr requested changes

2022-10-08 20:14 UTC, naanadr commented on index.html
> +            <h2 class="section-heading" style= "font-family: 'Roboto'; text-transform: capitalize; color: #000000; font-size: 20px; ">Eventos</h2>
Ficou faltando o "venha participar com a gente" que tinha anteriormente

2022-10-08 21:12 UTC, kailanefelix commented on index.html
> +            <h2 class="section-heading" style= "font-family: 'Roboto'; text-transform: capitalize; color: #000000; font-size: 20px; ">Eventos</h2>
@naanadr, achei que era pra fazer igual ao protótipo, não tinha esse subtítulo no Figma. Dá uma olhada lá e me diz se mudaram de ideia. Bjs.

2022-10-12 00:21 UTC, naanadr commented on index.html
> +            <h2 class="section-heading" style= "font-family: 'Roboto'; text-transform: capitalize; color: #000000; font-size: 20px; ">Eventos</h2>
@kailanefelix o figma não é a versão final, é passível de alterações. Mas beleza, vou aprovar porque realmente estavamos focando no figma, mas caso você queira depois sugerir alguma alteração, pode fazer :)

2022-10-12 00:22 UTC, naanadr approved these changes

2022-10-12 00:22 UTC, merged